# Generated by Django 4.1.3 on 2022-12-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raspisanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_raspisanie', models.CharField(max_length=255, verbose_name='Название.')),
                ('image_raspisanie', models.ImageField(upload_to='raspisanie_image/', verbose_name='Фотография')),
                ('created_raspisanie', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сабактардын жугуртмосу ',
                'verbose_name_plural': 'Сабактардын жугуртмосу ',
            },
        ),
    ]
