# Generated by Django 4.1.3 on 2022-12-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raspisanie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raspisanie',
            old_name='name_raspisanie',
            new_name='name',
        ),
    ]
