# Generated by Django 4.1.3 on 2022-12-18 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raspisanie', '0002_rename_name_raspisanie_raspisanie_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raspisanie',
            old_name='image_raspisanie',
            new_name='image',
        ),
    ]
