# Generated by Django 4.1.3 on 2022-12-01 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Жанылыктар', 'verbose_name_plural': 'Жанылыктар'},
        ),
    ]
