# Generated by Django 4.1.3 on 2022-12-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_location_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Аты!')),
                ('email', models.EmailField(max_length=254, verbose_name='Почтасы')),
                ('message', models.TextField(verbose_name='Кабары')),
            ],
            options={
                'verbose_name': 'Акыркы Кабарлар',
                'verbose_name_plural': 'Акыркы Кабарлар',
            },
        ),
    ]
