# Generated by Django 4.1.3 on 2022-12-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='About_image', verbose_name='Сурот')),
                ('name', models.CharField(max_length=244, verbose_name='Биз жонундо')),
                ('descriptions', models.TextField(verbose_name='Биз жонундо кошумча маалымат!')),
            ],
            options={
                'verbose_name': 'Биз жонундо маалымат',
                'verbose_name_plural': 'Биз жонундо кошумча маалыматтар',
            },
        ),
    ]
