# Generated by Django 4.1.1 on 2022-12-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_studet_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studet',
            name='desc_student',
            field=models.CharField(default=1, max_length=255, verbose_name='Класс жетекчисинин аты: .'),
            preserve_default=False,
        ),
    ]
