# Generated by Django 4.1.1 on 2022-12-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studet_desc_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studet',
            name='desc_student',
        ),
    ]
