# Generated by Django 4.1.3 on 2022-12-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='desc',
        ),
        migrations.AddField(
            model_name='parents',
            name='parents_doc',
            field=models.FileField(default=1, upload_to='parents_document/', verbose_name='Документ файл'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parents',
            name='name',
            field=models.CharField(max_length=244, verbose_name='Аты!'),
        ),
    ]
