# Generated by Django 4.1.3 on 2022-11-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_slide', models.ImageField(upload_to='slide_site/', verbose_name='Биринчи слайд')),
                ('second_slide', models.ImageField(upload_to='slide_site/', verbose_name='Второй слайд')),
                ('description_slide', models.TextField(verbose_name='Слайдка маалымат!')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайд',
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакттар', 'verbose_name_plural': 'Контакттар'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_site',
            field=models.CharField(max_length=255, verbose_name='Телефон номер'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='description_site',
            field=models.TextField(verbose_name='Мектеп боюнча маалымат'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='logo_site',
            field=models.ImageField(upload_to='logo_site/', verbose_name='Мектептин логотиби'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='name_site',
            field=models.CharField(max_length=244, verbose_name='Сайттын аты!'),
        ),
    ]
