# Generated by Django 4.1.3 on 2022-11-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_slide_alter_contact_options_alter_contact_phone_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_school', models.CharField(max_length=255, verbose_name='МЕКТЕПТИН НЕГИЗДЕЛГЕН ЖЫЛЫ')),
                ('child_school', models.CharField(max_length=255, verbose_name='ОКУУЧУЛАРДЫН САНЫ')),
                ('graduate_school', models.CharField(max_length=255, verbose_name='БҮТҮРҮҮЧҮЛӨР (ЖЫЛЫНА)')),
            ],
            options={
                'verbose_name': 'Мектеп боюнча маалымат',
                'verbose_name_plural': 'Мектеп боюнча маалымат ',
            },
        ),
    ]
