# Generated by Django 4.1.3 on 2022-11-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='book_school',
            field=models.CharField(default=1, max_length=255, verbose_name='КИТЕПТЕРДИН САНЫ'),
            preserve_default=False,
        ),
    ]
