# Generated by Django 4.1.3 on 2022-11-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_data_book_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=255, verbose_name='Сурот')),
            ],
            options={
                'verbose_name': 'Сертификаттар',
                'verbose_name_plural': 'Сертификаттар ',
            },
        ),
    ]
