# Generated by Django 4.1.3 on 2022-12-01 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_certificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
