# Generated by Django 4.1.3 on 2022-12-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_delete_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'Биз сандабыз!', 'verbose_name_plural': 'Биз сандабыз! '},
        ),
    ]
