# Generated by Django 4.1.3 on 2022-12-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_teacher', models.CharField(max_length=255, verbose_name='Мугалимдин аты.')),
                ('image_teacher', models.ImageField(upload_to='teacher_image/', verbose_name='Мугалимдин суроту')),
                ('description_teacher', models.TextField(verbose_name='Мугалимдин кызматы.')),
            ],
            options={
                'verbose_name': 'Мугалимдер',
            },
        ),
    ]
