# Generated by Django 4.1.1 on 2022-12-26 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AchykSaat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Аты')),
            ],
            options={
                'verbose_name': 'Ачык саат',
                'verbose_name_plural': 'Ачык саат',
            },
        ),
        migrations.CreateModel(
            name='AchykSaatDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achyksaat_file', models.FileField(upload_to='achyksaat/', verbose_name='Документ файл')),
                ('name', models.CharField(max_length=255, verbose_name='Аты')),
                ('accreditation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achyksaat', to='achyk.achyksaat', verbose_name='Ачык саат')),
            ],
            options={
                'verbose_name': 'Ачык саат болумго киргизуу',
                'verbose_name_plural': 'Ачык саат болумго киргизуу',
            },
        ),
    ]
