# Generated by Django 4.1.1 on 2022-12-26 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achyk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achyksaatdetail',
            old_name='achyksaat_file',
            new_name='achyksaat',
        ),
    ]
