# Generated by Django 4.1.1 on 2022-12-24 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Аты')),
            ],
            options={
                'verbose_name': 'Галерея ',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='GalleryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.ImageField(upload_to='gallery/', verbose_name='Сурот')),
                ('accreditation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accreditation', to='gallery.gallery', verbose_name='Галерея')),
            ],
            options={
                'verbose_name': 'Галерея  болумго киргизуу',
                'verbose_name_plural': 'Галерея  болумго киргизуу',
            },
        ),
    ]
