# Generated by Django 4.1.1 on 2022-12-26 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerydetail',
            name='accreditation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='gallery.gallery', verbose_name='Галерея'),
        ),
    ]
