# Generated by Django 4.1.3 on 2022-12-17 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcreditationList2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Аты')),
            ],
            options={
                'verbose_name': 'Программалык аккредитация',
                'verbose_name_plural': 'Программалык аккредитация',
            },
        ),
        migrations.CreateModel(
            name='AcreditationList2Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accreditation_detail', models.FileField(upload_to='accreditation/', verbose_name='Документ файл')),
                ('name', models.CharField(max_length=255, verbose_name='Аты')),
                ('accreditation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accreditation', to='prog_akred.acreditationlist2', verbose_name='Аккредитация')),
            ],
            options={
                'verbose_name': 'Программалык аккредитация болумго киргизуу',
                'verbose_name_plural': 'Программалык аккредитация болумго киргизуу',
            },
        ),
    ]
