# Generated by Django 4.1.3 on 2022-11-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_pride', models.ImageField(upload_to='image_pride/', verbose_name='Суроту!')),
                ('name_pride', models.CharField(max_length=255, verbose_name='Сыймыктанабыз')),
                ('description_pride', models.TextField(verbose_name='Кошумча маалымат!')),
            ],
            options={
                'verbose_name': 'Сыймыктанабыз!',
                'verbose_name_plural': 'Сыймыктанабыз!',
            },
        ),
    ]
